/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'desktop' : IDL.Null,
  'printers' : IDL.Null,
  'laptop' : IDL.Null,
  'allInOne' : IDL.Null,
  'peripherals' : IDL.Null,
});
export const Brand = IDL.Variant({ 'asus' : IDL.Null, 'epson' : IDL.Null });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'specs' : IDL.Text,
  'category' : Category,
  'brand' : Brand,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'desktop' : IDL.Null,
    'printers' : IDL.Null,
    'laptop' : IDL.Null,
    'allInOne' : IDL.Null,
    'peripherals' : IDL.Null,
  });
  const Brand = IDL.Variant({ 'asus' : IDL.Null, 'epson' : IDL.Null });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'specs' : IDL.Text,
    'category' : Category,
    'brand' : Brand,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };